### ISSUE TITLE
Smiting

### ISSUE THREAD

**Issue by samennis1** [ImmaFreedom-Dev/ImmaFreedomMod#123]
Hello,

I have noticed the fact that both console and telnet get spammed with the following message once someone is smited, I am not sure if there is a fix to this but thought I'd bring it up anyway as it spams the console and telnet of the server.

**The following part of this message is the spam that people get**

:[13:29:27 ERROR]: Could not pass event PlayerDeathEvent to stServerMessages v1.5.3org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396)
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417)
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:87)
	at me.StevenLawson.TotalFreedomMod.Commands.Command_smite.smite(Command_smite.java:75)
	at me.StevenLawson.TotalFreedomMod.Commands.Command_smite.run(Command_smite.java:37)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70)
	at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:241)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
	at me.StevenLawson.BukkitTelnet.session.ClientSession$1.run(ClientSession.java:204)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.shepherdjerred.stservermessages.listeners.DeathEvent.onPlayerDeath(DeathEvent.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	... 21 more

**Comment by OutOfYourMind** [comment]
Just do telnet.log and it stops logging that crap.

**Comment by aggelosQQ** [comment]
@OutOfYourMind what? It's an error that needs to be fixed, telnet.log is not a way to solve it, it just hides the errors, however, the errors still exist.
@RobinGall2910 @ImmaFreedom-Dev/developers @ImmaFreedom-Dev/jr-developers

**Comment by RobinGall2910** [comment]
@aggelosQQ 

Could not pass event PlayerDeathEvent to stServerMessages 

There's your problem. It's with the plug ServerMessages.

**Comment by aggelosQQ** [comment]
Mhm, tyler had removed 'em back them. I think the plugin is still forked, just compile it and add it.

**Comment by DUFCLiam** [comment]
I will re-add death messages :)

**Comment by RobinGall2910** [comment]
Fixed by me.
